[variables]
PYTHONPATH = "src"

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build phase'"]

[start]
cmd = ". /opt/venv/bin/activate && python -m uvicorn kopi_bot.main:app --host 0.0.0.0 --port $PORT"